language: android
android:
  components:
    - build-tools-24.0.0

    # The SDK version used to compile your project
    - android-21

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script: ./gradlew test connectedAndroidTest
